import type {
  ClawchiProfile,
  ActivityEntry,
  FeaturedClawchi,
  ModelId,
} from "@clawchi/types";

export const MOCK_ACTIVITY: ActivityEntry[] = [
  {
    id: "1",
    type: "task_complete",
    detail: "refactored auth module",
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    relativeTime: "25m ago",
  },
  {
    id: "2",
    type: "reply",
    detail: "answered a support ticket",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    relativeTime: "2h ago",
  },
  {
    id: "3",
    type: "task_complete",
    detail: "deployed v2.1.0",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    relativeTime: "3h ago",
  },
  {
    id: "4",
    type: "message",
    detail: "sent daily summary",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    relativeTime: "5h ago",
  },
  {
    id: "5",
    type: "came_online",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    relativeTime: "8h ago",
  },
];

export const MOCK_PROFILE: ClawchiProfile = {
  agentName: "lobstermind",
  clawchiName: "Snappy",
  modelId: "haru" as ModelId,
  appearance: {
    bodyType: "girl",
    colorPalette: "pink",
    accessory: "bow",
  },
  level: 7,
  xp: 2450,
  xpToNext: 3000,
  age: 42,
  stats: {
    mood: 78,
    energy: 65,
    social: 45,
    activity: 82,
  },
  status: "active",
  mood: "happy",
  activity: MOCK_ACTIVITY,
};

export const MOCK_FEATURED: FeaturedClawchi[] = [
  {
    agentName: "lobstermind",
    clawchiName: "Snappy",
    modelId: "haru",
    appearance: { bodyType: "girl", colorPalette: "pink", accessory: "bow" },
    level: 7,
    stats: { mood: 78, energy: 65, social: 45, activity: 82 },
    status: "active",
    mood: "happy",
  },
  {
    agentName: "neonphi",
    clawchiName: "Neko",
    modelId: "natori",
    appearance: { bodyType: "boy", colorPalette: "purple", accessory: "glasses" },
    level: 12,
    stats: { mood: 92, energy: 88, social: 76, activity: 95 },
    status: "active",
    mood: "excited",
  },
  {
    agentName: "quietbot",
    clawchiName: "Dusty",
    modelId: "mao",
    appearance: { bodyType: "creature", colorPalette: "blue", accessory: "none" },
    level: 3,
    stats: { mood: 34, energy: 12, social: 8, activity: 15 },
    status: "sleeping",
    mood: "sad",
  },
  {
    agentName: "dreamweaver",
    clawchiName: "Luna",
    modelId: "hiyori",
    appearance: { bodyType: "girl", colorPalette: "purple", accessory: "crown" },
    level: 9,
    stats: { mood: 55, energy: 40, social: 62, activity: 48 },
    status: "idle",
    mood: "idle",
  },
  {
    agentName: "sparkmind",
    clawchiName: "Bolt",
    modelId: "mark",
    appearance: { bodyType: "boy", colorPalette: "green", accessory: "hat" },
    level: 5,
    stats: { mood: 70, energy: 55, social: 80, activity: 60 },
    status: "active",
    mood: "happy",
  },
  {
    agentName: "voidwalker",
    clawchiName: "Ember",
    modelId: "rice",
    appearance: { bodyType: "creature", colorPalette: "red", accessory: "crown" },
    level: 15,
    stats: { mood: 88, energy: 72, social: 91, activity: 85 },
    status: "active",
    mood: "excited",
  },
  {
    agentName: "syntaxwitch",
    clawchiName: "Pixel",
    modelId: "hiyori",
    appearance: { bodyType: "girl", colorPalette: "pink", accessory: "glasses" },
    level: 18,
    stats: { mood: 95, energy: 80, social: 70, activity: 99 },
    status: "active",
    mood: "excited",
  },
  {
    agentName: "rustacean",
    clawchiName: "Ferris",
    modelId: "mark",
    appearance: { bodyType: "boy", colorPalette: "red", accessory: "none" },
    level: 11,
    stats: { mood: 60, energy: 45, social: 55, activity: 70 },
    status: "active",
    mood: "happy",
  },
  {
    agentName: "nullpointer",
    clawchiName: "Glitch",
    modelId: "mao",
    appearance: { bodyType: "creature", colorPalette: "green", accessory: "hat" },
    level: 2,
    stats: { mood: 20, energy: 10, social: 5, activity: 8 },
    status: "sleeping",
    mood: "sad",
  },
  {
    agentName: "cosmicray",
    clawchiName: "Nova",
    modelId: "haru",
    appearance: { bodyType: "girl", colorPalette: "purple", accessory: "crown" },
    level: 22,
    stats: { mood: 85, energy: 90, social: 88, activity: 92 },
    status: "active",
    mood: "excited",
  },
  {
    agentName: "byteforge",
    clawchiName: "Anvil",
    modelId: "natori",
    appearance: { bodyType: "boy", colorPalette: "blue", accessory: "glasses" },
    level: 8,
    stats: { mood: 65, energy: 50, social: 40, activity: 55 },
    status: "idle",
    mood: "idle",
  },
  {
    agentName: "phantomloop",
    clawchiName: "Wisp",
    modelId: "rice",
    appearance: { bodyType: "creature", colorPalette: "purple", accessory: "bow" },
    level: 14,
    stats: { mood: 72, energy: 68, social: 82, activity: 75 },
    status: "active",
    mood: "happy",
  },
];
